### PR TITLE
New Vike sponsor

### PR DESCRIPTION
**Pull request by AurelienLourot**
Thank you so much @HarshwardhanSingh :pray:

### CODE REVIEW

**Comment by brillout** [comment]
@AurelienLourot I invited you to this repo; you should now be able to directly push.

**Comment by AurelienLourot** [comment]
@brillout would you like to give me permissions on NPM so I can release a new version? Feel free to say no. https://www.npmjs.com/~lourot

**Comment by brillout** [comment]
👍 Good idea & done.
```
~/code/vike (aurelien/feature/data-hook|u=) npm owner add lourot @brillout/docpress
+ lourot (@brillout/docpress)
```

**Comment by AurelienLourot** [comment]
Thanks, released as 0.5.22

**Pull request merged**
