### PR TITLE
minor refactor

### PR DESCRIPTION
**Pull request by phonzammi**
@brillout 

What do you think ?
I believe that adding an ID attribute to the `<h1>` tag is essential

### CODE REVIEW

**Comment by brillout** [comment]
What's the benefit of turning the IDs into classes? :eyes:

**Comment by brillout** [comment]
> I believe that adding an ID attribute to the `<h1>` tag is essential

Why? How about adding a comment? (FYI there is a function `determineSectionUrlHash()` to turn any arbitrary string into an id although I don't know whether that's relevant for what you want to achieve.)

**Comment by phonzammi** [comment]
> What's the benefit of turning the IDs into classes? 👀

I'm not sure, but wdyt of this : https://docsearch.algolia.com/docs/tips/#set-a-unique-class-to-the-element-holding-the-content ?

**Comment by phonzammi** [comment]
> > I believe that adding an ID attribute to the `<h1>` tag is essential
> 
> Why? How about adding a comment? (FYI there is a function `determineSectionUrlHash()` to turn any arbitrary string into an id although I don't know whether that's relevant for what you want to achieve.)

Basically, every heading in `+Page.mdx` will be rendered with an ID when the page is displayed.
e.g. `## Typescript` => `<h2 id="typescript">TypeScript</h2>`.

except for `<h1>`, which is generated by PageLayout.tsx.

I took inspiration from the [Vite](https://vite.dev/) page for this implementation

**Comment by phonzammi** [comment]
> > I believe that adding an ID attribute to the `<h1>` tag is essential
> 
> Why? How about adding a comment? (FYI there is a function `determineSectionUrlHash()` to turn any arbitrary string into an id although I don't know whether that's relevant for what you want to achieve.)

Hmm, it accepts string while `pageTitle` is a `JSX.Element`

**Comment by brillout** [comment]
Hm, it seems all a bit fuzzy but let's merge if you think it can help. I've invited as a docpress collaborator, feel free to release a new docpress version, and then bump and deploy a new `vike.dev` and/or `telefunc.com` version.

**Comment by phonzammi** [comment]
Thank you, I'll see what I can do

**Comment by brillout** [comment]
> deploy a new `vike.dev` and/or `telefunc.com` version

Just invited you to be a Telefunc collaborator, IIRC you can already push to Vike's repository but let me know if you can't.

**Pull request merged**
