### PR TITLE
feat: use custom DocSearch `<Hit>` component

### PR DESCRIPTION
**Pull request by phonzammi**
Hi @brillout 

Here, we create a custom <Hit> component. All the newly added files are sourced from [Algolia's DocSearch repository](https://github.com/algolia/docsearch/tree/main/packages/docsearch-react/src) and modified as needed, since many of the types used are not exported.

I was thinking we could just fork the repo and publish our own package, since the only required change to achieve our goals is just one line of code: (if we fork the repo)

```diff
- attribute="hierarchy.lvl1"
+ attribute={hit.content ? 'content' : 'hierarchy.lvl1'}
```

https://github.com/algolia/docsearch/blob/9733ba9a503e18a27d5fef3470fde8b3bb54ec79/packages/docsearch-react/src/Results.tsx#L148

I also pushed a commit to remove the transformItem since we no longer need it. see https://github.com/brillout/docpress/commit/d3641d3590fc5942d815f0a4aedfc89e3d699cbd

### CODE REVIEW

**Comment by brillout** [comment]
> Here, we create a custom component. All the newly added files are sourced from [Algolia's DocSearch repository](https://github.com/algolia/docsearch/tree/main/packages/docsearch-react/src) and modified as needed, since many of the types used are not exported.

Is that what VuePress does as well?

**Comment by brillout** [comment]
How about we move `types/DocSearch.ts` to `components/Algolia/types.ts`?

> only required change to achieve our goals is just one line of code:

Maybe we can add a `README.md` that documents how the `components/Alogila/` directory was created.

**Comment by brillout** [comment]
> I was thinking we could just fork the repo and publish our own package

I guess defining `<Hit>` directly in this repo is easier for now?

**Comment by phonzammi** [comment]
> Is that what VuePress does as well?

Do you mean Vuetify? I'm not sure, but they use `vue-instantsearch` instead of Algolia's `@docsearch`. From what I’ve seen in their [code](https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/components/app/search), it looks even more complex.

**Comment by phonzammi** [comment]
> How about we move `types/DocSearch.ts` to `components/Algolia/types.ts`?

Sure

> Maybe we can add a `README.md` that documents how the `components/Alogila/` directory was created.

Okay, will do

**Comment by brillout** [comment]
:+1: I think we can merge then.

**Comment by phonzammi** [comment]
> > I was thinking we could just fork the repo and publish our own package
> 
> I guess defining `<Hit>` directly in this repo is easier for now?

Yeah, I think it is

**Comment by phonzammi** [comment]
What do you think of this Readme https://github.com/brillout/docpress/pull/11/commits/6ac67f624ed38606d8da8e6af7e6b808d63834c7 ?

**Comment by brillout** [comment]
Did a bit of polishing, feel free to revert.

> The components were modified to fit our needs. This included changing specific functionalities and adapting styles to match our application's design.

That sounds like a big change?

**Comment by brillout** [comment]
Otherwise LGTM :+1:

**Comment by phonzammi** [comment]
> Did a bit of polishing, feel free to revert.
> 
> > The components were modified to fit our needs. This included changing specific functionalities and adapting styles to match our application's design.
> 
> That sounds like a big change?

Yeah, it is indeed a big change. I have to combine the code from multiple components into one.

**Comment by brillout** [comment]
Good to know, I thought it was just some minor changes. Maybe I'd write a a couple of words about it, just as a high-level overview.

Although if we end up with a complete custom component then we can simply have a README that say "Our custom <Hit> implementation, for an improved UX. Forked from ..." that would do the trick then.

**Comment by brillout** [comment]
(My thinking being that , if there a lot of changes then tracking all changes isn't worth it, but if there only a couple minor changes then it could be worth it in order to make rebasing on top of changes to the source repository easier.)

**Comment by phonzammi** [comment]
So to be clear, (i also updated the first comment):
If we fork the repo, the diff is just one line, as mentioned in the first comment.

**Comment by brillout** [comment]
Ah, I see. I think I would clarify that in the README. It isn't clear as it is: it made me think that we introduced a lot of changes to the `<Hit>` component, but all the refactoring is actually only about extracting it from the rest of the code.

If we go for a custom style like Vuetify does, would it need changes to the `<Hit>` component? Or is it just a bunch of custom `!important` CSS overriding Algolia's CSS?

**Comment by phonzammi** [comment]
> Ah, I see. I think I would clarify that in the README.

Wdyt https://github.com/brillout/docpress/pull/11/commits/206dadc3feff1cab923623d8cd022ef066ef792d ?

**Comment by brillout** [comment]
My issue is with this:

>    - The components were modified to fit our needs. This included changing specific functionalities and adapting styles to match our application's design.
>   - Most notably, we created a custom `<Hit>` component to tailor the display of search results.

It sounds like a lot of new features have been implemented. But it's all just some "boring" refactoring, right?

**Comment by phonzammi** [comment]
Yeah, you're right, hmm, I mean we modified some functionality related to rendering the icons that came from outside the `<Hit>` component, and we did a bit of refactoring to include it inside.

**Comment by phonzammi** [comment]
> If we go for a custom style like Vuetify does, would it need changes to the `<Hit>` component? Or is it just a bunch of custom `!important` CSS overriding Algolia's CSS?

The `<Hit>` component is only apply to each of the hit :

docsearch-hit

If we go for a completely custom style like Vuetify does, we can use Algolia's [react-instantsearch](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react/).
> React InstantSearch is an open source UI library for React that lets you build a search interface in your frontend app.
InstantSearch focuses on enhancing your frontend with primitives that you can combine to create unique search interfaces.

**Comment by brillout** [comment]
> Algolia's [react-instantsearch](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react/).

Neat. Let's do that if we start diverging too much. I guess we don't need to maintain some kind of "fork documentation" then; thus merging as-is.

**Pull request merged**
