### PR TITLE
feat: support windows and cn hash

### PR DESCRIPTION
**Pull request by hemengke1997**
Hi! Here I did two things:
1. Fix the `acorn: Unterminated string constant ` issue on Windows system
2. Support chinese url hash by `\u4E00-\u9FA5`. (I'm not sure if this approach is good. If not, please tell me and I'll fix it) 😁

### CODE REVIEW

**Comment by brillout** [comment]
Uh neat 😊. I was actually just about to look at the bug you mentioned on Discord :-).

**Comment by brillout** [comment]
> 2\. Support chinese url hash by `\u4E00-\u9FA5`. (I'm not sure if this approach is good. If not, please tell me and I'll fix it)

I'm not sure either. I'd say: let's just try and see if it works. (FYI Vite's CN docs keeps the URL hash in English, e.g. https://cn.vitejs.dev/guide/features.html#hot-module-replacement.)

**Comment by hemengke1997** [comment]
> I'm not sure either. I'd say: let's just try and see if it works. (FYI Vite's CN docs keeps the URL hash in English, e.g. https://cn.vitejs.dev/guide/features.html#hot-module-replacement.)

Okay, I'll see how vite handles it then fix it when I'm free. Thanks for your suggestion.

**Comment by brillout** [comment]
👍 looking forward to 👀. Just released your patch as `0.3.2`.

**Pull request merged**
